#ifndef ECLAY_HRI_EVSYS_H
#define ECLAY_HRI_EVSYS_H

#include "hri/sam.h"

#include <stdbool.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef uint8_t hri_evsys_channel_t;
#define HRI_EVSYS_NUM_CHANNELS   EVSYS_CHANNELS

typedef enum
{
  HRI_EVSYS_USER_CHANNEL_NONE  = 0x0,
  HRI_EVSYS_USER_CHANNEL_0     = 0x1,
  HRI_EVSYS_USER_CHANNEL_1     = 0x2,
  HRI_EVSYS_USER_CHANNEL_2     = 0x3,
  HRI_EVSYS_USER_CHANNEL_3     = 0x4,
  HRI_EVSYS_USER_CHANNEL_4     = 0x5,
  HRI_EVSYS_USER_CHANNEL_5     = 0x6,
  HRI_EVSYS_USER_CHANNEL_6     = 0x7,
  HRI_EVSYS_USER_CHANNEL_7     = 0x8,
  HRI_EVSYS_USER_CHANNEL_8     = 0x9,
  HRI_EVSYS_USER_CHANNEL_9     = 0xA,
  HRI_EVSYS_USER_CHANNEL_10    = 0xB,
  HRI_EVSYS_USER_CHANNEL_11    = 0xC,
} hri_evsys_user_channel_t;

typedef enum
{
  HRI_EVSYS_EDGE_NO_OUTPUT = EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT_Val,
  HRI_EVSYS_EDGE_RISING    = EVSYS_CHANNEL_EDGSEL_RISING_EDGE_Val,
  HRI_EVSYS_EDGE_FALLING   = EVSYS_CHANNEL_EDGSEL_FALLING_EDGE_Val,
  HRI_EVSYS_EDGE_BOTH      = EVSYS_CHANNEL_EDGSEL_BOTH_EDGES_Val
} hri_evsys_edge_t;

typedef enum
{
  HRI_EVSYS_PATH_SYNCHRONOUS    = EVSYS_CHANNEL_PATH_SYNCHRONOUS_Val,
  HRI_EVSYS_PATH_RESYNCHRONIZED = EVSYS_CHANNEL_PATH_RESYNCHRONIZED_Val,
  HRI_EVSYS_PATH_ASYNCHRONOUS   = EVSYS_CHANNEL_PATH_ASYNCHRONOUS_Val
} hri_evsys_path_t;

typedef enum
{
  HRI_EVSYS_GENERATOR_NONE         = 0x00,

  HRI_EVSYS_GENERATOR_RTC_CMP0     = EVSYS_ID_GEN_RTC_CMP_0,
  HRI_EVSYS_GENERATOR_RTC_CMP1     = EVSYS_ID_GEN_RTC_CMP_1,
  HRI_EVSYS_GENERATOR_RTC_OVF      = EVSYS_ID_GEN_RTC_OVF,
  HRI_EVSYS_GENERATOR_RTC_PER0     = EVSYS_ID_GEN_RTC_PER_0,
  HRI_EVSYS_GENERATOR_RTC_PER1     = EVSYS_ID_GEN_RTC_PER_1,
  HRI_EVSYS_GENERATOR_RTC_PER2     = EVSYS_ID_GEN_RTC_PER_2,
  HRI_EVSYS_GENERATOR_RTC_PER3     = EVSYS_ID_GEN_RTC_PER_3,
  HRI_EVSYS_GENERATOR_RTC_PER4     = EVSYS_ID_GEN_RTC_PER_4,
  HRI_EVSYS_GENERATOR_RTC_PER5     = EVSYS_ID_GEN_RTC_PER_5,
  HRI_EVSYS_GENERATOR_RTC_PER6     = EVSYS_ID_GEN_RTC_PER_6,
  HRI_EVSYS_GENERATOR_RTC_PER7     = EVSYS_ID_GEN_RTC_PER_7,

  HRI_EVSYS_GENERATOR_EIC_EXTINT0  = EVSYS_ID_GEN_EIC_EXTINT_0,
  HRI_EVSYS_GENERATOR_EIC_EXTINT1  = EVSYS_ID_GEN_EIC_EXTINT_1,
  HRI_EVSYS_GENERATOR_EIC_EXTINT2  = EVSYS_ID_GEN_EIC_EXTINT_2,
  HRI_EVSYS_GENERATOR_EIC_EXTINT3  = EVSYS_ID_GEN_EIC_EXTINT_3,
  HRI_EVSYS_GENERATOR_EIC_EXTINT4  = EVSYS_ID_GEN_EIC_EXTINT_4,
  HRI_EVSYS_GENERATOR_EIC_EXTINT5  = EVSYS_ID_GEN_EIC_EXTINT_5,
  HRI_EVSYS_GENERATOR_EIC_EXTINT6  = EVSYS_ID_GEN_EIC_EXTINT_6,
  HRI_EVSYS_GENERATOR_EIC_EXTINT7  = EVSYS_ID_GEN_EIC_EXTINT_7,
  HRI_EVSYS_GENERATOR_EIC_EXTINT8  = EVSYS_ID_GEN_EIC_EXTINT_8,
  HRI_EVSYS_GENERATOR_EIC_EXTINT9  = EVSYS_ID_GEN_EIC_EXTINT_9,
  HRI_EVSYS_GENERATOR_EIC_EXTINT10 = EVSYS_ID_GEN_EIC_EXTINT_10,
  HRI_EVSYS_GENERATOR_EIC_EXTINT11 = EVSYS_ID_GEN_EIC_EXTINT_11,
  HRI_EVSYS_GENERATOR_EIC_EXTINT12 = EVSYS_ID_GEN_EIC_EXTINT_12,
  HRI_EVSYS_GENERATOR_EIC_EXTINT13 = EVSYS_ID_GEN_EIC_EXTINT_13,
  HRI_EVSYS_GENERATOR_EIC_EXTINT14 = EVSYS_ID_GEN_EIC_EXTINT_14,
  HRI_EVSYS_GENERATOR_EIC_EXTINT15 = EVSYS_ID_GEN_EIC_EXTINT_15,

  HRI_EVSYS_GENERATOR_DMAC_CH0     = EVSYS_ID_GEN_DMAC_CH_0,
  HRI_EVSYS_GENERATOR_DMAC_CH1     = EVSYS_ID_GEN_DMAC_CH_1,
  HRI_EVSYS_GENERATOR_DMAC_CH2     = EVSYS_ID_GEN_DMAC_CH_2,
  HRI_EVSYS_GENERATOR_DMAC_CH3     = EVSYS_ID_GEN_DMAC_CH_3,

  HRI_EVSYS_GENERATOR_TCC0_OVF     = EVSYS_ID_GEN_TCC0_OVF,
  HRI_EVSYS_GENERATOR_TCC0_TRG     = EVSYS_ID_GEN_TCC0_TRG,
  HRI_EVSYS_GENERATOR_TCC0_CNT     = EVSYS_ID_GEN_TCC0_CNT,
  HRI_EVSYS_GENERATOR_TCC0_MCX0    = EVSYS_ID_GEN_TCC0_MCX_0,
  HRI_EVSYS_GENERATOR_TCC0_MCX1    = EVSYS_ID_GEN_TCC0_MCX_1,
  HRI_EVSYS_GENERATOR_TCC0_MCX2    = EVSYS_ID_GEN_TCC0_MCX_2,
  HRI_EVSYS_GENERATOR_TCC0_MCX3    = EVSYS_ID_GEN_TCC0_MCX_3,

  HRI_EVSYS_GENERATOR_TCC1_OVF     = EVSYS_ID_GEN_TCC1_OVF,
  HRI_EVSYS_GENERATOR_TCC1_TRG     = EVSYS_ID_GEN_TCC1_TRG,
  HRI_EVSYS_GENERATOR_TCC1_CNT     = EVSYS_ID_GEN_TCC1_CNT,
  HRI_EVSYS_GENERATOR_TCC1_MCX0    = EVSYS_ID_GEN_TCC1_MCX_0,
  HRI_EVSYS_GENERATOR_TCC1_MCX1    = EVSYS_ID_GEN_TCC1_MCX_1,

  HRI_EVSYS_GENERATOR_TCC2_OVF     = EVSYS_ID_GEN_TCC2_OVF,
  HRI_EVSYS_GENERATOR_TCC2_TRG     = EVSYS_ID_GEN_TCC2_TRG,
  HRI_EVSYS_GENERATOR_TCC2_CNT     = EVSYS_ID_GEN_TCC2_CNT,
  HRI_EVSYS_GENERATOR_TCC2_MCX0    = EVSYS_ID_GEN_TCC2_MCX_0,
  HRI_EVSYS_GENERATOR_TCC2_MCX1    = EVSYS_ID_GEN_TCC2_MCX_1,

  HRI_EVSYS_GENERATOR_TC3_OVF      = EVSYS_ID_GEN_TC3_OVF,
  HRI_EVSYS_GENERATOR_TC3_MC0      = EVSYS_ID_GEN_TC3_MCX_0,
  HRI_EVSYS_GENERATOR_TC3_MC1      = EVSYS_ID_GEN_TC3_MCX_1,

  HRI_EVSYS_GENERATOR_TC4_OVF      = EVSYS_ID_GEN_TC4_OVF,
  HRI_EVSYS_GENERATOR_TC4_MC0      = EVSYS_ID_GEN_TC4_MCX_0,
  HRI_EVSYS_GENERATOR_TC4_MC1      = EVSYS_ID_GEN_TC4_MCX_1,

  HRI_EVSYS_GENERATOR_TC5_OVF      = EVSYS_ID_GEN_TC5_OVF,
  HRI_EVSYS_GENERATOR_TC5_MC0      = EVSYS_ID_GEN_TC5_MCX_0,
  HRI_EVSYS_GENERATOR_TC5_MC1      = EVSYS_ID_GEN_TC5_MCX_1,

  HRI_EVSYS_GENERATOR_ADC_RESRDY   = EVSYS_ID_GEN_ADC_RESRDY,
  HRI_EVSYS_GENERATOR_ADC_WINMON   = EVSYS_ID_GEN_ADC_WINMON,

  HRI_EVSYS_GENERATOR_AC_COMP0     = EVSYS_ID_GEN_AC_COMP_0,
  HRI_EVSYS_GENERATOR_AC_COMP1     = EVSYS_ID_GEN_AC_COMP_1,
  HRI_EVSYS_GENERATOR_AC_WIN0      = EVSYS_ID_GEN_AC_WIN_0,

  HRI_EVSYS_GENERATOR_DAC_EMPTY    = EVSYS_ID_GEN_DAC_EMPTY,

  HRI_EVSYS_GENERATOR_PTC_EOC      = 0x48,
  HRI_EVSYS_GENERATOR_PTC_WCOMP    = 0x49,
} hri_evsys_generator_t;

typedef enum
{
  HRI_EVSYS_USER_DMAC_CH0   = EVSYS_ID_USER_DMAC_CH_0,
  HRI_EVSYS_USER_DMAC_CH1   = EVSYS_ID_USER_DMAC_CH_1,
  HRI_EVSYS_USER_DMAC_CH2   = EVSYS_ID_USER_DMAC_CH_2,
  HRI_EVSYS_USER_DMAC_CH3   = EVSYS_ID_USER_DMAC_CH_3,

  HRI_EVSYS_USER_TCC0_EV0   = EVSYS_ID_USER_TCC0_EV_0,
  HRI_EVSYS_USER_TCC0_EV1   = EVSYS_ID_USER_TCC0_EV_1,
  HRI_EVSYS_USER_TCC0_MC0   = EVSYS_ID_USER_TCC0_MC_0,
  HRI_EVSYS_USER_TCC0_MC1   = EVSYS_ID_USER_TCC0_MC_1,
  HRI_EVSYS_USER_TCC0_MC2   = EVSYS_ID_USER_TCC0_MC_2,
  HRI_EVSYS_USER_TCC0_MC3   = EVSYS_ID_USER_TCC0_MC_3,

  HRI_EVSYS_USER_TCC1_EV0   = EVSYS_ID_USER_TCC1_EV_0,
  HRI_EVSYS_USER_TCC1_EV1   = EVSYS_ID_USER_TCC1_EV_1,
  HRI_EVSYS_USER_TCC1_MC0   = EVSYS_ID_USER_TCC1_MC_0,
  HRI_EVSYS_USER_TCC1_MC1   = EVSYS_ID_USER_TCC1_MC_1,

  HRI_EVSYS_USER_TCC2_EV0   = EVSYS_ID_USER_TCC2_EV_0,
  HRI_EVSYS_USER_TCC2_EV1   = EVSYS_ID_USER_TCC2_EV_1,
  HRI_EVSYS_USER_TCC2_MC0   = EVSYS_ID_USER_TCC2_MC_0,
  HRI_EVSYS_USER_TCC2_MC1   = EVSYS_ID_USER_TCC2_MC_1,

  HRI_EVSYS_USER_TC3        = EVSYS_ID_USER_TC3_EVU,

  HRI_EVSYS_USER_TC4        = EVSYS_ID_USER_TC4_EVU,

  HRI_EVSYS_USER_TC5        = EVSYS_ID_USER_TC5_EVU,

  HRI_EVSYS_USER_ADC_START  = EVSYS_ID_USER_ADC_START,
  HRI_EVSYS_USER_ADC_SYNC   = EVSYS_ID_USER_ADC_SYNC,

  HRI_EVSYS_USER_AC_COMP0   = EVSYS_ID_USER_AC_SOC_0,
  HRI_EVSYS_USER_AC_COMP1   = EVSYS_ID_USER_AC_SOC_0,

  HRI_EVSYS_USER_DAC_START  = EVSYS_ID_USER_DAC_START,

  HRI_EVSYS_USER_PTC_STCONV = 0x1C,
} hri_evsys_user_t;

typedef enum
{
  HRI_EVSYS_INTERRUPT_DETECT,
  HRI_EVSYS_INTERRUPT_OVERRUN,
} hri_evsys_interrupt_t;

typedef void (*hri_evsys_interrupt_callback_t)( hri_evsys_channel_t channel, hri_evsys_interrupt_t interrupt );


void HRI_EVSYS_Initialize( void );

void HRI_EVSYS_User_Set(
    hri_evsys_user_t user,
    hri_evsys_user_channel_t channel
  );

void HRI_EVSYS_Generator_Set(
    hri_evsys_generator_t generator,
    hri_evsys_channel_t channel,
    hri_evsys_edge_t edge,
    hri_evsys_path_t path
  );

void HRI_EVSYS_SoftwareTrigger(
    hri_evsys_channel_t channel
  );

bool HRI_EVSYS_isChannelBusy(
    hri_evsys_channel_t channel
  );

bool HRI_EVSYS_isChannelUserReady(
    hri_evsys_channel_t channel
  );


void HRI_EVSYS_InterruptCallback_Set(
    hri_evsys_channel_t channel,
    hri_evsys_interrupt_callback_t callback
  );

void HRI_EVSYS_Interrupt_Enable(
    hri_evsys_channel_t channel,
    hri_evsys_interrupt_t interrupt
  );

void HRI_EVSYS_Interrupt_Disable(
    hri_evsys_channel_t channel,
    hri_evsys_interrupt_t interrupt
  );

bool HRI_EVSYS_InterruptFlag_Get(
    hri_evsys_channel_t channel,
    hri_evsys_interrupt_t interrupt
  );

void HRI_EVSYS_InterruptFlag_Clear(
    hri_evsys_channel_t channel,
    hri_evsys_interrupt_t interrupt
  );


#ifdef __cplusplus
}
#endif

#endif  // ECLAY_HRI_EVSYS_H
